### ISSUE TITLE
Replace iOS oral history app with kiosk app

### ISSUE THREAD

**Issue by vantuyls** [osulp/kiosks#172]
Currently, we  have an iOS application for listening to oral histories (video or audio) on an iPad. The goal of this epic would be to replace the iOS app with a version of the kiosk app. Requirements include:
- [ ] ability to display a grid of A/V files on the tablet homepage withe some basic metadata
- [ ] when the user selects from the file grid, that file pops up a new window that allows the user to play the A/V and see basic metadata about the file
- [ ] ability to manage content (add, remove, replace, reorder files)

Possible enhancements include:
- [ ] showing a transcript of the A/V file while the file is playing (higher priority)
- [ ] ability to run the application offline (lower priority)
