### ISSUE TITLE
Revamp layout theming for admin area of application [Migrate from rails_admin]

### ISSUE THREAD

**Issue by straleyb** [osulp/kiosks#465]
This is to layout the need to revamp the layout for a majority of the back office area. We are just using bootstrap panels which is bleh. We can update this to make it more visually appealing. This can be done in the process of migrating away from rails_admin as well so we dont have two back office areas. 

- [ ] Kiosks splash page
- [ ] Collections CRUD pages
- [ ] Slides CRUD pages (also remove captions or make overflow:scroll)
- [ ] Kiosks CRUD
- [ ] Create user CRUD
- [ ] Create Kiosk Layout CRUD
- [ ] Create Slide Type CRUD
